# Generated by Django 4.2.5 on 2023-10-11 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes_site.category'),
            preserve_default=False,
        ),
    ]
