# Generated by Django 4.2.5 on 2023-10-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_site', '0002_recipe_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category_id',
        ),
    ]
