# Generated by Django 4.2.5 on 2023-10-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_site', '0004_remove_recipe_author_cookingitem_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Горячее', 'Горячее'), ('Холодное', 'Холодное'), ('Закуска', 'Закуска'), ('Десерт', 'Десерт')], max_length=50),
        ),
    ]
