# Generated by Django 4.2.5 on 2023-10-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_site', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Горячее', 'Горячее'), ('Холодное', 'Холодное'), ('Закуска', 'Закуска'), ('Десерт', 'Десерт')], max_length=50, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='create_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Фото блюда'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.CharField(max_length=300, verbose_name='Описание'),
        ),
    ]
